fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [lambda, scripts, tests]
      - id: ruff-format
        args: [lambda, scripts, tests, --check]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
  - repo: https://github.com/pdm-project/pdm
    rev: 2.10.3
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, --without-hashes, --prod]
        files: ^pdm.lock$
      - id: pdm-lock-check
