import os

STRAVA_TOKENS_TABLE_NAME = os.environ["STRAVA_TOKENS_TABLE_NAME"]
ACCESS_TOKEN_KEY = os.environ["ACCESS_TOKEN_KEY"]
REFRESH_TOKEN_KEY = os.environ["REFRESH_TOKEN_KEY"]

STRAVA_CLIENT_ID = os.environ["STRAVA_CLIENT_ID"]
STRAVA_CLIENT_SECRET = os.environ["STRAVA_CLIENT_SECRET"]
